### PR TITLE
Fix UI/streaming timeouts for long running LLM requests

### LINKED ISSUE #869: [BUG] Streaming chat shows "no visible reply" for a long time; later cancels and backend logs cleanup warnings
## Summary

In the UI, streaming chats sometimes show no visible incremental reply for a long period. Eventually the request may cancel/time out on the frontend, and backend logs include cleanup warnings (e.g., `Runner.close() was cancelled` and MCP cancel‑scope messages). Users perceive this as the chat "hanging" or failing, and it can occasionally correlate with probe failures under load.

## Version / Environment

- kagent version: 0.5.5 (also observed on latest main)
- UI image with embedded Nginx reverse proxy
- A2A streaming via Next.js route `/a2a/{namespace}/{agent}`

## Steps To Reproduce

1. Deploy UI and Controller, create a streaming Agent (e.g., AIRE‑agent).
2. Start a chat and observe the browser network panel for `/a2a/...`.
3. In certain runs, there are no incremental SSE events visible for an extended time; later the request cancels or ends.

## Expected Behavior

- The chat shows incremental updates in real time while the agent processes the request.

## Actual Behavior

- The chat appears to have no reply for a long time.
- The request may cancel/time out on the frontend.
- Backend logs show cleanup‑phase warnings and cancellations.

## Evidence / Logs

Examples seen in backend logs:

```
WARNING:google_adk...: Runner.close() was cancelled; suppressing during cleanup
ERROR asyncio: Exception in callback EventConsumer.agent_task_callback()
...
asyncio.exceptions.CancelledError: Cancelled by cancel scope ...
Warning: Error during MCP session cleanup ... Attempted to exit cancel scope in a different task than it was entered in
```

## Impact

- Users see chats that appear stuck or fail.
- May cascade into timeouts/cancellations and occasional probe failures under pressure.

## Additional Context

- Similar user symptoms were reported in #859.
### 📋 Prerequisites

- [x] I have searched the [existing issues](./issues) to avoid creating a duplicate
- [x] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kagent-dev/kagent/blob/main/CODE_OF_CONDUCT.md)
- [x] I am using the latest version of the software
- [x] I have tried to clear cache/cookies or used incognito mode (if ui-related)
- [x] I can consistently reproduce this issue

### 🎯 Affected Service(s)

UI Service

### 🚦 Impact/Severity

No impact (Default)

## Summary

In the UI, streaming chats sometimes show no visible incremental reply for a long period. Eventually the request may cancel/time out on the frontend, and backend logs include cleanup warnings (e.g., `Runner.close() was cancelled` and MCP cancel‑scope messages). Users perceive this as the chat "hanging" or failing, and it can occasionally correlate with probe failures under load.

## Version / Environment

- kagent version: 0.5.5 (also observed on latest main)
- UI image with embedded Nginx reverse proxy
- A2A streaming via Next.js route `/a2a/{namespace}/{agent}`

## Steps To Reproduce

1. Deploy UI and Controller, create a streaming Agent (e.g., AIRE‑agent).
2. Start a chat and observe the browser network panel for `/a2a/...`.
3. In certain runs, there are no incremental SSE events visible for an extended time; later the request cancels or ends.

## Expected Behavior

- The chat shows incremental updates in real time while the agent processes the request.

## Actual Behavior

- The chat appears to have no reply for a long time.
- The request may cancel/time out on the frontend.
- Backend logs show cleanup‑phase warnings and cancellations.

## Evidence / Logs

Examples seen in backend logs:

```
WARNING:google_adk...: Runner.close() was cancelled; suppressing during cleanup
ERROR asyncio: Exception in callback EventConsumer.agent_task_callback()
...
asyncio.exceptions.CancelledError: Cancelled by cancel scope ...
Warning: Error during MCP session cleanup ... Attempted to exit cancel scope in a different task than it was entered in
```

## Impact

- Users see chats that appear stuck or fail.
- May cascade into timeouts/cancellations and occasional probe failures under pressure.

## Additional Context

- Similar user symptoms were reported in #859.

### 🔄 Steps To Reproduce

1. Open the UI and initiate a streaming chat with a configured Agent.
2. Observe the network panel for the `/a2a/{namespace}/{agent}` request.
3. Note that incremental SSE events may not appear for an extended time, followed by cancellation.

### 🤔 Expected Behavior

Chat should stream incremental responses in real time without long gaps or unexpected cancellation.

### 📱 Actual Behavior

- Long period with no visible incremental output.
- Stream cancels/times out; backend logs show cleanup warnings.

### 💻 Environment

- kagent 0.5.5 and latest main
- UI with embedded Nginx, Next.js proxy route `/a2a/...`
- Browser: Chrome/Edge (latest)

### 🔧 CLI Bug Report

_No response_

### 🔍 Additional Context

_No response_

### 📋 Logs

```shell
WARNING:google_adk...: Runner.close() was cancelled; suppressing during cleanup
ERROR asyncio: Exception in callback EventConsumer.agent_task_callback()
...
asyncio.exceptions.CancelledError: Cancelled by cancel scope ...
Warning: Error during MCP session cleanup ... Attempted to exit cancel scope in a different task than it was entered in
```

### 📷 Screenshots

_No response_

### 🙋 Are you willing to contribute?

- [ ] I am willing to submit a PR to fix this issue

### LINKED ISSUE #892: [BUG] client timeout when invoking and agent referencing other agents
### 📋 Prerequisites

- [x] I have searched the [existing issues](./issues) to avoid creating a duplicate
- [x] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kagent-dev/kagent/blob/main/CODE_OF_CONDUCT.md)
- [x] I am using the latest version of the software
- [x] I have tried to clear cache/cookies or used incognito mode (if ui-related)
- [x] I can consistently reproduce this issue

### 🎯 Affected Service(s)

Multiple services / System-wide issue

### 🚦 Impact/Severity

No impact (Default)

### 🐛 Bug Description

When an agent references other agents, the call times out.

Controller:

```
2025-09-12T19:00:45Z    ERROR   client/client.go:259    Error reading SSE stream for request : context deadline exceeded (Client.Timeout or context cancellation while reading body)
```

### 🔄 Steps To Reproduce

1. Create a new agent
2. Add other agents to it
3. invoke it

### 🤔 Expected Behavior

_No response_

### 📱 Actual Behavior

_No response_

### 💻 Environment

_No response_

### 🔧 CLI Bug Report

_No response_

### 🔍 Additional Context

_No response_

### 📋 Logs

```shell

```

### 📷 Screenshots

_No response_

### 🙋 Are you willing to contribute?

- [ ] I am willing to submit a PR to fix this issue

### PR DESCRIPTION
**Pull request by onematchfox**
Whilst API interaction with Agents may use a streaming connection the agents themselves [do not use streaming](https://github.com/kagent-dev/kagent/blob/5c99583b505cbc205bcf1503ffdb1b241abf08c9/python/packages/kagent-adk/src/kagent/adk/converters/request_converter.py#L32) when communicating with the model .Thus, if a model takes longer than 60s to run (looking at you `gpt-5`) then things start timing out. 

This PR:
- increases the default timeout on the A2A streaming connections in the controller to 10mins (this is a thumbsuck number and was chosen to match the [default timeout](https://github.com/google/adk-python/blame/main/src/google/adk/agents/remote_a2a_agent.py#L86) used by Google on non-streaming `RemoteA2AAgent` calls)
- adds a keep-alive implementation to the UI A2A proxy to prevent the streaming connection from being closed prematurely
- fixes the streaming timeout in the UI client-side code (again using 10 minutes before timing out)

Closes #869

Potentially also related to/resolves #892?

### CODE REVIEW

File: ui/src/app/a2a/[namespace]/[agentName]/route.ts [hunk 1]
```diff
@@ -49,20 +49,39 @@ export async function POST(
...
+          }
+        };
+
+        // Keep-alive timer logic
+        const resetKeepAliveTimer = () => {
+          if (keepAliveTimer) clearTimeout(keepAliveTimer);
+          keepAliveTimer = setTimeout(sendKeepAlive, KEEP_ALIVE_INTERVAL_MS);
+        };
 
         const pump = (): Promise<void> => {
```
[the remark this answers is not in the document]
Comment (onematchfox) [reply ui/src/app/a2a/[namespace]/[agentName]/route.ts:75]: Keep-alive timer is reset (aka started) once the first event is processed (and after every event thereafter).

File: helm/kagent/values.yaml [hunk 2]
```diff
@@ -72,7 +72,7 @@ controller:
   streaming: # Streaming buffer size for A2A communication
     maxBufSize: 1Mi # 1024 * 1024
     initialBufSize: 4Ki # 4 * 1024
-    timeout: 60s # 60 seconds
+    timeout: 600s # 600 seconds
```
Comment (EItanya) [inline helm/kagent/values.yaml:75]: 👍

File: ui/src/app/a2a/[namespace]/[agentName]/route.ts [hunk 3]
```diff
@@ -49,20 +49,39 @@ export async function POST(
...
           return reader.read().then(({ done, value }): Promise<void> => {
             if (done) {
               if (!isClosed) {
+                if (keepAliveTimer) clearTimeout(keepAliveTimer);
                 controller.close();
                 isClosed = true;
+                console.log('A2A Proxy: Backend connection closed.');
```
Comment (peterj) [inline ui/src/app/a2a/[namespace]/[agentName]/route.ts:82]: leftover from debugging/testjng?

**Review by EItanya — APPROVED** [review]

File: ui/src/app/a2a/[namespace]/[agentName]/route.ts (hunk 3 above)
Comment (onematchfox) [reply ui/src/app/a2a/[namespace]/[agentName]/route.ts:82]: Yeah leftover but intentionally so - had to add logging to try understand when and why various connections were closed. Left it as it may prove useful to others in future.
