### PR TITLE
add model creation to the UI + nav fixes to accommodate for new funct…

### LINKED ISSUE #255: add an option of creating modelconfig through the UI

### PR DESCRIPTION
**Pull request by peterj**
…ionality

Fixes #255

### CODE REVIEW

File: go/controller/internal/httpserver/handlers/modelconfig.go [hunk 1]
```diff
@@ -60,10 +134,543 @@ func (h *ModelConfigHandler) HandleGetModelConfig(w ErrorResponseWriter, r *http
...
+		log.Error(nil, "API key is required for non-Ollama providers")
+		w.RespondWithError(errors.NewBadRequestError("API key is required for this provider", nil))
+		return
+	}
+
+	// For Ollama, use a placeholder value if apiKey is empty, as secret data cannot be truly empty
+	if isOllama && apiKey == "" {
+		apiKey = "ollama-no-key"
+		log.V(1).Info("Ollama provider selected, using placeholder for secret data")
+	}
```
Comment (EItanya) [inline go/controller/internal/httpserver/handlers/modelconfig.go]: Can we just fix this issue in the translator?

File: go/controller/internal/httpserver/handlers/modelconfig.go [hunk 2]
```diff
@@ -60,10 +134,543 @@ func (h *ModelConfigHandler) HandleGetModelConfig(w ErrorResponseWriter, r *http
...
+			log.V(1).Info("Cannot set model parameter during update", "parameter", key)
+		}
+	}
+	log.V(1).Info("Successfully validated and populated new provider config for update")
+
+	// --- Update Secret if API Key is provided (and not Ollama) ---
+	secretName := configName
+	secretKey := fmt.Sprintf("%s_API_KEY", strings.ToUpper(req.Provider.Type))
+	isOllama := strings.EqualFold(req.Provider.Type, string(v1alpha1.Ollama))
+	shouldUpdateSecret := req.APIKey != nil && *req.APIKey != ""
```
Comment (EItanya) [inline go/controller/internal/httpserver/handlers/modelconfig.go]: Same comment

File: go/controller/internal/httpserver/handlers/modelconfig.go [hunk 3]
```diff
@@ -60,10 +137,499 @@ func (h *ModelConfigHandler) HandleGetModelConfig(w ErrorResponseWriter, r *http
...
+	}
+
+	RespondWithJSON(w, http.StatusOK, providersResponse)
+}
+
+type CreateModelConfigRequest struct {
+	Name            string                      `json:"name"`
+	Provider        Provider                    `json:"provider"`
+	Model           string                      `json:"model"`
+	APIKey          string                      `json:"apiKey"`
```
Comment (EItanya) [inline go/controller/internal/httpserver/handlers/modelconfig.go:258]: Should this be optional here as well. Allow the user to point to an existing secret?

File: go/controller/internal/httpserver/handlers/modelconfig.go [hunk 4]
```diff
@@ -60,10 +137,499 @@ func (h *ModelConfigHandler) HandleGetModelConfig(w ErrorResponseWriter, r *http
...
+
+	log.V(1).Info("Updating ModelConfig spec")
+	modelConfig.Spec.OpenAI = nil
+	modelConfig.Spec.Anthropic = nil
+	modelConfig.Spec.AzureOpenAI = nil
+	modelConfig.Spec.Ollama = nil
+
+	modelConfig.Spec.Model = req.Model
+	modelConfig.Spec.Provider = v1alpha1.ModelProvider(req.Provider.Name)
+	modelConfig.Spec.APIKeySecretKey = secretKey
```
Comment (EItanya) [inline go/controller/internal/httpserver/handlers/modelconfig.go]: Rather than doing this, can you just set `ModelConfig.Spec = ModelConfigSpec{}`. Are there any fields that need to stay the same?

**Review by EItanya — CHANGES_REQUESTED** [review]

File: go/controller/internal/httpserver/handlers/modelconfig.go (hunk 3 above)
Comment (peterj) [reply go/controller/internal/httpserver/handlers/modelconfig.go:258]: will do in a separate PR -- allow the users to pick an existing secret vs. create a new one

File: go/controller/internal/httpserver/handlers/modelconfig.go (hunk 1 above)
Comment (peterj) [reply go/controller/internal/httpserver/handlers/modelconfig.go]: are you saying to move the code that creates the secret to the translator?

Comment (EItanya) [reply go/controller/internal/httpserver/handlers/modelconfig.go]: Ahhh, no no no, I just meant validating, we shouldn't need to create a secret for Ollama at all

**Review by EItanya — APPROVED** [review]
