### PR TITLE
fix: use oTEL Context instead of LogRecord

### LINKED ISSUE #1366: [BUG] `LogDeprecatedInitWarning` spam when OTEL logging is enabled
### 📋 Prerequisites

- [x] I have searched the [existing issues](./issues) to avoid creating a duplicate
- [x] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kagent-dev/kagent/blob/main/CODE_OF_CONDUCT.md)
- [x] I am using the latest version of the software
- [x] I have tried to clear cache/cookies or used incognito mode (if ui-related)
- [x] I can consistently reproduce this issue

### 🎯 Affected Service(s)

Multiple services / System-wide issue

### 🚦 Impact/Severity

Minor inconvenience

### 🐛 Bug Description

When enabling OpenTelemetry logging in kagent, the application continuously emits the following warning:

```
/.kagent/.venv/lib/python3.13/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py:337: LogDeprecatedInitWarning: LogRecord init with `trace_id`, `span_id`, and/or `trace_flags` is deprecated since 1.35.0. Use `context` instead.
```

This warning appears repeatedly during runtime and floods the logs.

### 🔄 Steps To Reproduce

1. Enable Otel Logging.

### 🤔 Expected Behavior

No `LogDeprecatedInitWarning` log messages.

### 📱 Actual Behavior

Most of the agents interactions result in these `LogDeprecatedInitWarning` logs.

### 💻 Environment

- Kubeadm cluster in version 1.34
- kagent on version 0.7.17

### 🔧 CLI Bug Report

_No response_

### 🔍 Additional Context

_No response_

### 📋 Logs

```shell
/.kagent/.venv/lib/python3.13/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py:337: LogDeprecatedInitWarning: LogRecord init with `trace_id`, `span_id`, and/or `trace_flags` is deprecated since 1.35.0. Use `context` instead.
  return cls(
/.kagent/.venv/lib/python3.13/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py:337: LogDeprecatedInitWarning: LogRecord init with `trace_id`, `span_id`, and/or `trace_flags` is deprecated since 1.35.0. Use `context` instead.
  return cls(
/.kagent/.venv/lib/python3.13/site-packages/opentelemetry/sdk/_events/__init__.py:53: LogDeprecatedInitWarning: LogRecord init with `trace_id`, `span_id`, and/or `trace_flags` is deprecated since 1.35.0. Use `context` instead.
  log_record = LogRecord(
/.kagent/.venv/lib/python3.13/site-packages/opentelemetry/sdk/_events/__init__.py:53: LogDeprecatedInitWarning: LogRecord init with `trace_id`, `span_id`, and/or `trace_flags` is deprecated since 1.35.0. Use `context` instead.
  log_record = LogRecord(
/.kagent/.venv/lib/python3.13/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py:337: LogDeprecatedInitWarning: LogRecord init with `trace_id`, `span_id`, and/or `trace_flags` is deprecated since 1.35.0. Use `context` instead.
  return cls(
/.kagent/.venv/lib/python3.13/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py:337: LogDeprecatedInitWarning: LogRecord init with `trace_id`, `span_id`, and/or `trace_flags` is deprecated since 1.35.0. Use `context` instead.
  return cls(
/.kagent/.venv/lib/python3.13/site-packages/opentelemetry/sdk/_events/__init__.py:53: LogDeprecatedInitWarning: LogRecord init with `trace_id`, `span_id`, and/or `trace_flags` is deprecated since 1.35.0. Use `context` instead.
  log_record = LogRecord(
/.kagent/.venv/lib/python3.13/site-packages/opentelemetry/sdk/_events/__init__.py:53: LogDeprecatedInitWarning: LogRecord init with `trace_id`, `span_id`, and/or `trace_flags` is deprecated since 1.35.0. Use `context` instead.
  log_record = LogRecord(
/.kagent/.venv/lib/python3.13/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py:337: LogDeprecatedInitWarning: LogRecord init with `trace_id`, `span_id`, and/or `trace_flags` is deprecated since 1.35.0. Use `context` instead.
  return cls(
```

### 📷 Screenshots

_No response_

### 🙋 Are you willing to contribute?

- [ ] I am willing to submit a PR to fix this issue

### PR DESCRIPTION
**Pull request by EItanya**
Updates oTEL libraries to get rid of the spam logged deprecation warning

Fixes #1366

### CODE REVIEW

File: go/test/e2e/invoke_api_test.go [hunk 1]
```diff
@@ -252,40 +256,50 @@ func runStreamingTest(t *testing.T, a2aClient *a2aclient.A2AClient, userMessage,
...
-		msgResult, ok := event.Result.(*protocol.TaskStatusUpdateEvent)
-		if !ok {
-			continue
+		resultList := []protocol.StreamingMessageEvent{}
+		for event := range stream {
+			msgResult, ok := event.Result.(*protocol.TaskStatusUpdateEvent)
+			if !ok {
+				continue
+			}
+			if msgResult.Status.Message != nil {
```
Comment (jmhbh) [inline go/test/e2e/invoke_api_test.go]: nit: unused conditional

Comment (EItanya) [reply go/test/e2e/invoke_api_test.go]: Fixed

File: .claude/skills/run-e2e-tests/SKILL.md [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+
+## Prerequisites
+
+1. A running Kind cluster with kagent deployed:
+   ```bash
+   make create-kind-cluster
+   make helm-install
+   ```
+
+2. Test agent images built and pushed to the local registry (for BYO agent tests):
```
Comment (supreme-gg-gg) [inline .claude/skills/run-e2e-tests/SKILL.md:18]: perhaps tell claude to run `make push-test-agent && push-test-skill` so it doesn't need to bother finding out where the skill and sample agents are

**Review by supreme-gg-gg — APPROVED** [review]
