### PR TITLE
fix(ui): add support for Ollama model tags in the UI

### LINKED ISSUE #307: [BUG] Allow providing model tags for Ollama models
### 📋 Prerequisites

- [x] I have searched the [existing issues](./issues) to avoid creating a duplicate
- [x] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kagent-dev/kagent/blob/main/CODE_OF_CONDUCT.md)
- [x] I am using the latest version of the software
- [x] I have tried to clear cache/cookies or used incognito mode (if ui-related)
- [x] I can consistently reproduce this issue

### 🎯 Affected Service(s)

UI Service

### 🚦 Impact/Severity

No impact (Default)

### 🐛 Bug Description

We default to the :latest tag for Ollama models. In the UI we should add an input box that would allow users to explicitly set the model tag they want to use (e.g. qwen2.5:05.b). 

Note that it's not possible to pick specific tags in the UI as of right now (we always default to latest), but you can do it by updating the ModelConfig resource.

### 🔄 Steps To Reproduce

see above

### 🤔 Expected Behavior

_No response_

### 📱 Actual Behavior

_No response_

### 💻 Environment

_No response_

### 🔧 CLI Bug Report

_No response_

### 🔍 Additional Context

_No response_

### 📋 Logs

```shell

```

### 📷 Screenshots

_No response_

### 🙋 Are you willing to contribute?

- [ ] I am willing to submit a PR to fix this issue

### PR DESCRIPTION
**Pull request by sbx0r**
This PR /resolves #307 issue. It adds ability to specify custom model tags when creating or editing Ollama model configurations in the UI

Changes:
- Added a "Model Tag" input field that appears only when Ollama provider is selected
- Default tag value is set to "latest" when not specified
- Automatically includes the tag in the model name when it's different from "latest"
- Sends the model name to the API in the format model:tag when a custom tag is specified
- Stores the tag value in the model parameters for reference
- Updates the auto-generated model resource name to include the tag for better identification
- The tag input helps users specify which version of an Ollama model they want to use, making it easier to work with different versions of the same model.

The tag input helps users specify which version of an Ollama model they want to use, making it easier to work with different versions of the same model.

> [!IMPORTANT]
> This change currently **prevents updating** the model tag on existing ModelProvider resources.
>
> **Here’s why:**
> When using the automatic name generator, the resulting ModelProvider name follows the convention
> {provider}-{model}-{tag} — for example, ollama-starcoder2-3b.
> If the tag is changed without updating the resource name, it may lead to confusion — e.g., a model named ollama-deepseek-r1-7b might actually point to 70b, or vice versa.
>
> To ensure stability, the controller must either:
>   - guarantee that all dependent Teams/Agents will use the updated model, or
>   - prohibit such updates altogether.
>
> This needs to be discussed further.

--- 

After this PR merges the 'Create New Model' card looks like this:
- [non-ollama]
image
- [ollama with latest tag]
image
- [ollama with non-latest tag]
image

Resulting model will look like this:

- [ui]
image
- [resulting k8s manifest]
  ```yaml
   apiVersion: kagent.dev/v1alpha1
   kind: ModelConfig
   metadata:
     name: ollama-dolphin-mistral-70b
     namespace: kagent
   spec:
     apiKeySecretKey: ""
     apiKeySecretRef: ""
     model: dolphin-mistral:70b
     ollama: {}
     provider: Ollama
  ```

### CODE REVIEW

File: ui/src/app/models/new/page.tsx [hunk 1]
```diff
@@ -366,13 +384,27 @@ function ModelPageContent() {
...
     setErrors({});
 
+    let finalModelName = name.trim();
+    let finalModelWithTag = modelName;
+    if (finalSelectedProvider.type === 'Ollama' && modelTag.trim() !== 'latest') {
+      if (!isEditingName && !isEditMode) {
+        const tagSuffix = `-${modelTag.trim()}`;
+        finalModelName = finalModelName + tagSuffix;
+
+        if (!isResourceNameValid(finalModelName)) {
```
Comment (peterj) [inline ui/src/app/models/new/page.tsx]: recently I added `createRFC1123ValidName` -- perhaps use that to create the name? (so you don't have to check whether it's valid and use a regex).

File: ui/src/app/models/new/page.tsx [hunk 2]
```diff
@@ -264,14 +278,18 @@ function ModelPageContent() {
       if (parts.length === 2) {
         const providerKey = parts[0];
         const modelName = parts[1];
-        const baseName = `${providerKey}-${modelName}`.toLowerCase();
+        let baseName = `${providerKey}-${modelName}`.toLowerCase();
+        const isOllama = selectedProvider?.type === "Ollama";
+        if (isOllama && modelTag && modelTag !== 'latest') {
```
Comment (peterj) [inline ui/src/app/models/new/page.tsx]: nit: create a constant outside of the component for `latest` (E.g. `const LATEST_TAG="latest"`)

File: ui/src/app/models/new/page.tsx [hunk 3]
```diff
@@ -114,6 +114,7 @@ function ModelPageContent() {
   const [providerModelsData, setProviderModelsData] = useState<ProviderModelsResponse | null>(null);
   const [selectedCombinedModel, setSelectedCombinedModel] = useState<string | undefined>(undefined);
   const [selectedModelSupportsFunctionCalling, setSelectedModelSupportsFunctionCalling] = useState<boolean | null>(null);
```
Comment (peterj) [inline ui/src/app/models/new/page.tsx:117]: perhaps you can do the change in the wizard as well as a separate PR (doesn't have to be part of this one). Thanks a ton for doing this!

**Review by peterj — CHANGES_REQUESTED** [review]

**Comment by peterj** [comment]
another issue I noticed -- looks like the "0.5b" tag is applied twice to the name (I think this will be probably resolved once you switch to the method to create valid name).

Screenshot 2025-05-04 at 2 43 35 PM

**Comment by peterj** [comment]
also, check that the editing works - it looks like the provider is not filled out and the tag is readonly
Screenshot 2025-05-04 at 2 50 06 PM
as well -- right now, it

File: ui/src/app/models/new/page.tsx (hunk 3 above)
Comment (sbx0r) [reply ui/src/app/models/new/page.tsx:117]: My pleasure!
I'm flexible. If you'd like this change quickly, I can open a follow-up issue an PR.
LMK what works best for you.

**Comment by sbx0r** [comment]
> another issue I noticed -- looks like the "0.5b" tag is applied twice to the name (I think this will be probably resolved once you switch to the method to create valid name).
> 
> Screenshot 2025-05-04 at 2 43 35 PM

Thanks for checking it out!
I’ll use your validator and run it against the edge case you spotted.

**Comment by sbx0r** [comment]
> also, check that the editing works - it looks like the provider is not filled out and the tag is readonly Screenshot 2025-05-04 at 2 50 06 PM as well -- right now, it

Yup. I found the issue with empty provider but didn't want to add noise to the PR. I can fix it here if that's okay with you.
For the model tag lock - I've some thoughts. Please check the PR description (see the 'Important' section)

File: ui/src/app/models/new/page.tsx (hunk 1 above)
Comment (sbx0r) [reply ui/src/app/models/new/page.tsx]: current implementation of createRFC1123ValidName have this logic

```ts
  //...

  // Final validation check - though sanitization should make it valid
  if (!isResourceNameValid(combined)) {
      console.warn(`Generated name '${combined}' is still not RFC 1123 valid after sanitization.`);
      // Returning potentially invalid name, caller should ideally re-validate
      // Or return "" to indicate failure? Returning the attempt might be more informative.
      return combined;
  }

  //...
```

Could you tell why is it there?

Comment (peterj) [reply ui/src/app/models/new/page.tsx]: good point -- I think that was just a check in case it still couldn't create the valid name; I think we could keep this as is and see if anyone even runs into it.

File: ui/src/app/models/new/page.tsx (hunk 3 above)
Comment (peterj) [reply ui/src/app/models/new/page.tsx:117]: it's up to you -- if you don't mind adding it as part of this PR that would be good. but if not, a separate pr/issue is great as well.

**Comment by peterj** [comment]
> > also, check that the editing works - it looks like the provider is not filled out and the tag is readonly Screenshot 2025-05-04 at 2 50 06 PM as well -- right now, it
> 
> Yup. I found the issue with empty provider but didn't want to add noise to the PR. I can fix it here if that's okay with you. For the model tag lock - I've some thoughts. Please check the PR description (see the 'Important' section)

It would be a pain to go and update all agents when renaming the model; but I don't want to prevent people from updating the models once they created them. Perhaps we can only allow editing the models parameters (e.g. API key, baseUrl, etc.) but not the actual model name/tag.

File: ui/src/app/models/new/page.tsx (hunk 1 above)
Comment (sbx0r) [reply ui/src/app/models/new/page.tsx]: alright. should I validate again after the function call or the console.warn will be enough?

Comment (peterj) [reply ui/src/app/models/new/page.tsx]: I think warn should be enough -- and we'll see in which scenarios users run into this (if ever)

File: ui/src/app/models/new/page.tsx (hunk 3 above)
Comment (sbx0r) [reply ui/src/app/models/new/page.tsx:117]: I will add it to this PR then :)

File: ui/src/app/models/new/page.tsx (hunk 2 above)
Comment (sbx0r) [reply ui/src/app/models/new/page.tsx]: done

File: ui/src/app/models/new/page.tsx (hunk 3 above)
Comment (sbx0r) [reply ui/src/app/models/new/page.tsx:117]: done

**Comment by sbx0r** [comment]
All is done.
I also added minor UX improvement to the wizard (set dynamic `model config name` if not entered manually by user) and fixed provider icons to make 'em visible in both - light and dark modes.

Ohh...
and I modified helm to expose the port of the engine (8083) which helps a lot in local development

File: helm/kagent/templates/deployment.yaml [hunk 4]
```diff
@@ -50,6 +50,10 @@ spec:
           {{- with .Values.controller.env }}
             {{- toYaml . | nindent 12 }}
           {{- end }}
+          ports:
+            - name: http
+              containerPort: {{ .Values.service.ports.controller.targetPort }}
```
Comment (peterj) [inline helm/kagent/templates/deployment.yaml:55]: @EItanya you fine with exposing this (mostly for testing purposes)?

Comment (EItanya) [reply helm/kagent/templates/deployment.yaml:55]: Yea I don't see why not, seems good to have anyway

Comment (sbx0r) [reply helm/kagent/templates/deployment.yaml:55]: Just a heads-up - once the engine, controller, and UI are running in separate pods, we'll need to expose this port anyway. Right now, they're all sharing the same network interface.

**Comment by peterj** [comment]
@sbx0r  Looks like there are some linting errors in the UI (you can run `npm run build` locally to see the issues/fix them:))

**Comment by sbx0r** [comment]
> @sbx0r Looks like there are some linting errors in the UI (you can run `npm run build` locally to see the issues/fix them:))

Thanks!
I'm working on it.
Should be ready in a minute

Sorry for that. I was tesing it via `npm run dev` and forgot to run `make` before pinging you

**Comment by peterj** [comment]
@sbx0r , looks like that one issue I mentioned earlier is still there -- if I use the tag "0.5b", in the creation page, the name of the resource looks right (e.g. `ollama-qwen2-5-0-5b`), however, when the resource is actually created, it creates "ollama-qwen2-5-0-5b-0.5b".

**Comment by sbx0r** [comment]
> @sbx0r , looks like that one issue I mentioned earlier is still there -- if I use the tag "0.5b", in the creation page, the name of the resource looks right (e.g. `ollama-qwen2-5-0-5b`), however, when the resource is actually created, it creates "ollama-qwen2-5-0-5b-0.5b".

hmmm.....
Looks like an issue related to the OS/Browser/etc.

It works like a charm on my machine
image

image

**Comment by sbx0r** [comment]
could you please tell me something more about your environment @peterj?

**Comment by peterj** [comment]
you're completely right; this was me -- the GH pull request extension doesn't actually refresh the PR so I had old code -- anyway. it works -- let's wait for the CI and it's good to go!

**Comment by sbx0r** [comment]
Great to hear (that it's not a platform issue LoL 😄)!

**Review by peterj — APPROVED** [review]

**Review by EItanya — APPROVED** [review]
