### PR TITLE
fix: propagate MCPServer CRD timeout to RemoteMCPServer

### LINKED ISSUE #1272: [BUG] Default MCP server connection timeout (5s) is too low for sidecar gateway deployments, causing intermittent "Failed to create MCP session" errors
### 📋 Prerequisites

- [x] I have searched the [existing issues](./issues) to avoid creating a duplicate
- [x] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/kagent-dev/kagent/blob/main/CODE_OF_CONDUCT.md)
- [x] I am using the latest version of the software
- [x] I have tried to clear cache/cookies or used incognito mode (if ui-related)
- [x] I can consistently reproduce this issue

### 🎯 Affected Service(s)

Controller Service

### 🚦 Impact/Severity

Blocker

### 🐛 Bug Description

When an agent references MCP tools via `MCPServer` CRDs, the agent pod intermittently fails with:

```
Failed to create MCP session: Failed to connect to MCP server at http://localhost:8081/mcp: [Errno 111] Connection refused
```

or times out silently, causing the entire tool call to fail.

**Root cause:** The Python ADK's `StreamableHTTPConnectionParams` has a hardcoded default `timeout: float = 5.0` (see [mcp_session_manager.py](https://github.com/google/adk-python/blob/main/src/google/adk/tools/mcp_tool/mcp_session_manager.py)). When users deploy a `MCPServer` CRD, the kagent controller automatically generates a corresponding `RemoteMCPServer` resource. However:

1. The `MCPServer` CRD **does not expose a `timeout` field** for users to configure
2. The auto-generated `RemoteMCPServer` therefore has `spec.timeout: nil`
3. The controller does **not** populate a default timeout in the agent's `config.json`
4. The Python ADK falls back to its own 5-second default

**Why 5 seconds is insufficient:** MCP servers deployed via the `MCPServer` CRD use a sidecar [agentgateway](https://github.com/kagent-dev/agentgateway) container that spawns a new stdio process (e.g. via `uvx` or `npx`) for each MCP session. Process startup time depends heavily on:

- **Package cache state:** Cold starts (first invocation, new pod, or cache miss) require downloading/installing the MCP server package via `uvx` or `npx`. Even well-known MCP servers like `awslabs.eks-mcp-server`  can take **2–8 seconds** on cold starts.
- **Sequential initialization:** When an agent references multiple `MCPServer` tools, each tool's sidecar spawns its own stdio process. These initializations happen sequentially during tool discovery (`list_tools`), compounding startup time.
- **PR #1220 impact:** Since [#1220](https://github.com/kagent-dev/kagent/pull/1220) (v0.7.10), a new MCP session is created for every A2A request rather than being reused across calls. This means the stdio process startup penalty is paid on **every single request**, not just the first one.

**Typical failure pattern observed:**

- Cold starts (first call after pod creation): **frequently timeout** — stdio process installation + initialization exceeds 5s
- Warm calls: **intermittently timeout** — natural variability in stdio process spawn time via the sidecar gateway causes 10-30% of requests to exceed 5s, even when the package is cached

The timeout is per-MCP-server, but a single slow initialization is enough to fail the entire agent request.

### 🔄 Steps To Reproduce

1. Deploy kagent with the default configuration
2. Create a `MCPServer` CRD (e.g. any stdio-based MCP server like `@modelcontextprotocol/server-filesystem`):
   ```yaml
   apiVersion: kagent.dev/v1alpha1
   kind: MCPServer
   metadata:
     name: eks-mcp
   spec:
     transportType: stdio
     stdioTransport:
       command: uvx
       args: ["awslabs.eks-mcp-server@latest"]
   ```
   Note: The `MCPServer` CRD **does not have a `timeout` field** — users cannot configure this directly.
3. Create an `Agent` that references this MCPServer as a tool
4. Send a message to the agent that requires using the MCP tool
5. Observe intermittent `"Failed to create MCP session"` errors, especially on:
   - The first call after pod creation (cold start)
   - Under load when multiple agents are spawning stdio processes simultaneously
   - After the agentgateway sidecar restarts or cache is cleared

### 🤔 Expected Behavior

Agents using `MCPServer` CRDs should connect reliably to their MCP tool servers. Since the `MCPServer` CRD does not expose a timeout field, the controller should apply a sensible default that accommodates stdio process startup time via the sidecar gateway.

Proposed Solution: Make the default configurable via Helm values / controller config (recommended)

Add a global `defaultMCPServerTimeout` setting to the kagent controller configuration (exposed via Helm values). This allows cluster operators to tune the default without modifying code:

```yaml
# values.yaml
controller:
  defaultMCPServerTimeout: 30s
```

### 📱 Actual Behavior

Agents intermittently fail to create MCP sessions because the 5-second default timeout from the Python ADK is too low for the sidecar gateway architecture where a new stdio process is spawned per session.

### 💻 Environment

- **kagent version:** 0.7.13 (also affects all versions since #1220 / v0.7.10)
- **Python ADK version:** latest (confirmed `timeout: float = 5.0` default in `StreamableHTTPConnectionParams`)
- **Kubernetes:** EKS 1.34
- **MCP servers affected:** Any stdio-based MCP server deployed via `MCPServer` CRD, especially those using `npx` or `uvx`
- **agentgateway version:** 0.10.2

### 🔧 CLI Bug Report

_No response_

### 🔍 Additional Context

- **Related issues:** #631 (one broken ToolServer breaks all agents), #892 (client timeout with multi-agent), #1232 (controller locking up with bad MCP config)
- **Related PRs:** #1220 (new MCP session per request — increases exposure to this timeout), #907 (streaming timeout fix — different timeout, A2A level)
- **Key architectural detail:** `MCPServer` CRDs do **not** expose a `timeout` field to users. The controller auto-generates a `RemoteMCPServer` from each `MCPServer`, and only the `RemoteMCPServer` CRD has a `spec.timeout` field (which is optional). When nil, no default is currently applied by the controller, causing the Python ADK to fall back to 5s.
- The `terminateOnClose` field defaults to `true` in the Python ADK already, so no change is needed there

### 📋 Logs

```shell

```

### 📷 Screenshots

_No response_

### 🙋 Are you willing to contribute?

- [x] I am willing to submit a PR to fix this issue

### PR DESCRIPTION
**Pull request by skhedim**
Closes #1272
Supersedes #1275

### Summary

Propagates the new `Timeout` field from the MCPServer CRD (added in [kagent-dev/kmcp#121](https://github.com/kagent-dev/kmcp/pull/121)) to the generated `RemoteMCPServer` resources, fixing intermittent `"Failed to create MCP session"` errors for sidecar gateway deployments.

### Context

[#1272](https://github.com/kagent-dev/kagent/issues/1272) reported that the default 5s MCP connection timeout is too low for MCPServer CRD deployments where the sidecar gateway spawns stdio processes (via `uvx`/`npx`) with 2–8s cold starts.

An initial approach ([#1275](https://github.com/kagent-dev/kagent/pull/1275)) made the timeout configurable via Helm chart values, threading it through 6+ layers (Helm → ConfigMap → env → flag → handlers → translator). Per [maintainer feedback](https://github.com/kagent-dev/kagent/pull/1275#issuecomment-), the proper fix is to add the timeout directly to the MCPServer CRD.

### Approach

Instead of global controller-level configuration, the timeout is now a **per-resource field** on the MCPServer CRD with a kubebuilder default of `30s` (see [kagent-dev/kmcp#121](https://github.com/kagent-dev/kmcp/pull/121)).

`ConvertMCPServerToRemoteMCPServer` now propagates:
- **`Timeout`** from `MCPServerSpec` → `RemoteMCPServerSpec` (defaults to 30s via CRD)
- **`TerminateOnClose: true`** (matches ADK expected behavior for managed servers)

### Changes

| File | Description |
|------|-------------|
| `go/go.mod` | Bump kmcp dependency to version with `Timeout` field (kmcp version 0.2.6) |
| `go/internal/controller/translator/agent/adk_api_translator.go` | `ConvertMCPServerToRemoteMCPServer` propagates `Timeout` and sets `TerminateOnClose: true` |
| `go/internal/controller/translator/agent/testdata/outputs/agent_with_proxy_mcpserver.json` | Golden test updated |

### Backward Compatibility

- Default timeout is `30s`, matching the previous hardcoded behavior from #1275.
- When `MCPServer.Spec.Timeout` is explicitly set, that value takes precedence.
- `RemoteMCPServer` resources created directly (not via MCPServer CRD) are unaffected — they continue using their own `Spec.Timeout` field.

### Depends on

- [x] [kagent-dev/kmcp#121](https://github.com/kagent-dev/kmcp/pull/121) must be merged and released first
- [x] Update `go.mod` to replace the `replace` directive with the actual released version

### Testing

- All existing unit tests pass
- Golden test outputs regenerated
- `go build ./...` and `go test ./internal/controller/...` pass cleanly

### CODE REVIEW

File: go/internal/controller/translator/agent/adk_api_translator.go [hunk 1]
```diff
@@ -1259,16 +1266,30 @@ func ConvertMCPServerToRemoteMCPServer(mcpServer *v1alpha1.MCPServer) (*v1alpha2
...
 		ObjectMeta: metav1.ObjectMeta{
 			Name:      mcpServer.Name,
 			Namespace: mcpServer.Namespace,
 		},
 		Spec: v1alpha2.RemoteMCPServerSpec{
-			URL:      fmt.Sprintf("http://%s.%s:%d/mcp", mcpServer.Name, mcpServer.Namespace, mcpServer.Spec.Deployment.Port),
-			Protocol: v1alpha2.RemoteMCPServerProtocolStreamableHttp,
+			URL:              fmt.Sprintf("http://%s.%s:%d/mcp", mcpServer.Name, mcpServer.Namespace, mcpServer.Spec.Deployment.Port),
+			Protocol:         v1alpha2.RemoteMCPServerProtocolStreamableHttp,
+			TerminateOnClose: ptr.To(true),
```
Comment (EItanya) [inline go/internal/controller/translator/agent/adk_api_translator.go]: What does this do? Is this something we want to automatically enable for every MCP connection?

Comment (skhedim) [reply go/internal/controller/translator/agent/adk_api_translator.go]: Good catch, it's out of scope for this PR (which focuses on timeout). Removed in the latest force-push.

For context: it was added to match the `+kubebuilder:default=true` on `RemoteMCPServerSpec.TerminateOnClose`, since this struct is built in-memory and never goes through API server defaulting. 

That said, the sibling `ConvertServiceToRemoteMCPServer` doesn't set it either, so leaving it `nil` is consistent with existing behavior.
